#!/bin/bash
-rw-r--r-- 1 root root 61 Feb  8 03:04 0-current_working_directory -rw-r--r-- 1 root root 61 Feb  8 03:04 1-listit -rw-r--r-- 1 root root 17 Feb  8 03:12 2-bring_me_home  -rw-r--r-- 1 root root 10 Feb  8 03:04 README.md
