#!/bin/bash
drwxr-xr-x 2 root root 97 Feb  8 03:12 .                                                                            
drwxr-xr-x 4 root root 60 Feb  8 03:04 ..                                                                           
-rw-r--r-- 1 root root 61 Feb  8 03:04 0-current_working_directory                                                  
-rw-r--r-- 1 root root 61 Feb  8 03:04 1-listit                                                                     
-rw-r--r-- 1 root root 17 Feb  8 03:12 2-bring_me_home                                                              
-rw-r--r-- 1 root root 10 Feb  8 03:04 README.md
